# Generated by Django 4.1.5 on 2023-02-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField()),
                ('key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_run_time', models.DateTimeField()),
                ('job_state', models.BinaryField()),
            ],
        ),
    ]
